# Site settings
title: The Astromech Factory
description: The Astromech Factory is a fun little project born at HETIC and made by five 2nd year students. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sdancermichel.me/work/astromechfactory" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# FTP settings
ftp_host: 's171897.gridserver.com'
ftp_dir: '/domains/sdancermichel.me/html/astromechfactory'
ftp_passive: false
# FTP optional settings
ftp_port: 21                  # default 21
ftp_username: 'sdancermichel.me'     # default read from stdin
ftp_password: '&eD1n*v,Cb0' # default read from stdin